package source

import (
	"github.com/cloudhands/packet"
)

const (

	PKT_RECORD_TYPE_SESSION_TCP=1
	PKT_RECORD_TYPE_SESSION_UDP=2
	PKT_RECORD_TYPE_ICMP = 3
	PKT_RECORD_TYPE_ARP = 4
	PKT_RECORD_TYPE_OTHER = 5

	PKT_RECORD_TYPE_UDP_DNS = 6
	PKT_RECORD_TYPE_UDP_TFTP = 7
	PKT_RECORD_TYPE_UDP_SMON = 8

	PKT_RECORD_TYPE_TCP_HTTP = 9
	PKT_RECORD_TYPE_TCP_MAIL = 10
	PKT_RECORD_TYPE_TCP_FTP  = 11
	PKT_RECORD_TYPE_TCP_TELNET = 12
	PKT_RECORD_TYPE_TCP_SMON = 13
	PKT_RECORD_TYPE_MREQ_HTTP = 14
	PKT_RECORD_TYPE_MREQ_MAIL = 15
	PKT_RECORD_TYPE_TCP_FTP_DATA = 16
	PKT_RECORD_TYPE_TCP_SSH = 17
	PKT_RECORD_TYPE_TCP_MYSQL = 18

)

type PacketParser interface {

	Parse(ptype uint8,data []byte) packet.SourceEntry

}



